name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull lazycat911/midterm:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 80:5000 --name cicd-container lazycat911/midterm
